import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import tailwind from "@astrojs/tailwind";
import compress from "astro-compress";

// https://astro.build/config
export default defineConfig({
  site: "https://jakemulley.com",
  integrations: [
    mdx(),
    sitemap(),
    tailwind(),
    compress({
      HTML: {
        "html-minifier-terser": {
          caseSensitive: false,
          collapseInlineTagWhitespace: false,
          collapseWhitespace: true,
          continueOnParseError: false,
          html5: true,
          ignoreCustomComments: [/^!/, /^\s*#/],
          includeAutoGeneratedTags: true,
          keepClosingSlash: false,
          minifyCSS: false,
          minifyJS: false,
          minifyURLs: false,
          noNewlinesBeforeTagClose: false,
          preventAttributesEscaping: false,
          processConditionalComments: false,
          processScripts: [],
          quoteCharacter: '"',
          removeAttributeQuotes: false,
          removeComments: true,
          removeScriptTypeAttributes: false,
          removeStyleLinkTypeAttributes: false,
          removeTagWhitespace: false,
          sortAttributes: false,
          sortClassName: false,
          trimCustomFragments: false,
          useShortDoctype: true,
        },
      },
    }),
  ],
});
