name: Build jakemulley.com

on:
  pull_request:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - run: npm run build
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        commit_message: Build jakemulley.com
